name: "Deployment Workflow"

on:
  workflow_dispatch:
    inputs:
      deploymentobject:
        description: Deploy or Destroy infrastructure
        required: true
        default: "codebuild"
        type: choice
        options:
          - "codebuild"
          - "ecs"
          - "ec2"
      deploymenttype:
        description: Deploy or Destroy infrastructure
        required: true
        default: "deploy"
        type: choice
        options:
          - "deploy"
          - "destroy"
      name:
        required: true
        default: "runner"
      projectName:
        required: true
        default: "github-group"
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_ROLE:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  tf_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: install dependencies
        run: |
          npm install --force
          npm install -g cdktf-cli@latest --force
      - name: Config credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT}}:role/${{secrets.AWS_ROLE}}
          role-session-name: ${{secrets.AWS_ROLE}}
          aws-region: us-east-2
      - name: CDKTF Deployment
        run: |
          cdktf --app "npx ts-node ${{ inputs.deploymentobject }}-deployment.ts" synth
          cdktf --app "npx ts-node ${{ inputs.deploymentobject }}-deployment.ts" ${{ inputs.deploymenttype }} "*" --auto-approve
        env:
          VPC_ID: ${{ secrets.VPC_ID }}
          STATE_BUCKET: ${{ secrets.BUCKET_NAME }}
          SUBNET: ${{ secrets.SUBNET_ID }}
          SUBNET_2: ${{ secrets.SUBNET_TWO }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          REPOSITORY: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          RUNNER_NAME: ${{ inputs.name }}
          RUNNER_PROJECT: ${{ inputs.projectName }}
