name: ECS Deployment
on: 
  workflow_dispatch:
    inputs:
      deploymenttype:
        description: Deploy or Destroy infrastructure
        required: true
        default: "deploy"
        type: choice
        options:
          - "deploy"
          - "destroy"
      ResourceName:
        required: true
        default: "runner"
      projectName:
        required: true
        default: "github-group"
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_ROLE:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  container-image-push:
    runs-on: codebuild-runner-github-group-codebuild-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        if: ${{ github.event.inputs.deploymenttype == 'deploy' }}
        uses: actions/checkout@v2
      - name: Deploy GitHub-Runner Image
        if: ${{ github.event.inputs.deploymenttype == 'deploy' }}
        run: |
              cd docker

              sed -ie "s/{NAME}/$RESOURCE_NAME/g" entrypoint.sh
              sed -ie "s/{PROJECt}/$RESOURCE_PROJECT/g" entrypoint.sh
              sed -ie "s/{REPO_OWNER}/$REPO_OWNER/g" entrypoint.sh
              ###### To deploy to personal account uncomment the lower line ####
              #sed -ie "s/{REPOSITORY}/$REPOSITORY/g" entrypoint.sh

              docker build -t github-runner:latest . 
              aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com
              docker tag github-runner:latest ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com/github-runner:latest
              docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com/github-runner:latest
        env:
          REPOSITORY: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          RESOURCE_NAME: ${{ inputs.name }}
          RESOURCE_PROJECT: ${{ inputs.projectName }}
      - name: Deploy GitHub-Runner Image
        if: ${{ github.event.inputs.deploymenttype == 'destroy' }}
        run: |
          aws ecr batch-delete-image \
          --repository-name github-runner \
          --image-ids imageTag=latest 
  deploy-cluster:
    needs: container-image-push
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      resourceName: "${{ inputs.resourceName }}"
      projectName: "${{ inputs.projectName }}"
      deploymenttype: "${{ inputs.deploymenttype }}"
      deploymentobject: "ecs"
    secrets: inherit
