name: ECS Deployment
on: 
  workflow_dispatch:
    inputs:
      deploymenttype:
        description: Deploy or Destroy infrastructure
        required: true
        default: "deploy"
        type: choice
        options:
          - "deploy"
          - "destroy"
      name:
        required: true
        default: "runner"
      projectName:
        required: true
        default: "github-group"
jobs:
  container-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GitHub-Runner Image
        if: ${{ github.event.inputs.deploymenttyp == 'deploy' }}
        run: |
              cd docker

              sed -ie "s/{NAME}/$RUNNER_NAME/g" /entrypoint.sh
              sed -ie "s/{PROJECt}/$RUNNER_PROJECT/g" /entrypoint.sh
              sed -ie "s/{REPO_OWNER}/$REPO_OWNER/g" /entrypoint.sh
              ###### To deploy to personal account uncomment the lower line ####
              #sed -ie "s/{REPOSITORY}/$REPOSITORY/g" entrypoint.sh

              docker build -t github-runner:latest . 
              aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com
              docker tag github-runner:latest ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com/github-runner:latest
              docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.us-east-2.amazonaws.com/github-runner:latest
        env:
          REPOSITORY: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          RUNNER_NAME: ${{ inputs.name }}
          RUNNER_PROJECT: ${{ inputs.projectName }}
  deploy-cluster:
    uses: ./.github/workflows/deployment-workflow.yml
    with:
      name: "${{ inputs.name }}"
      projectName: "${{ inputs.projectName }}"
      deploymenttype: "${{ inputs.deploymenttype }}"
      deploymentobject: "ecs"
